/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoorwaardenRouteImport } from './routes/voorwaarden'
import { Route as VisieRouteImport } from './routes/visie'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ToegankelijkheidRouteImport } from './routes/toegankelijkheid'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AanbodRouteImport } from './routes/aanbod'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OverOnsIndexRouteImport } from './routes/over-ons.index'
import { Route as AanbodIndexRouteImport } from './routes/aanbod.index'
import { Route as OverOnsVerhaalRouteImport } from './routes/over-ons.verhaal'
import { Route as OverOnsMissieVisieRouteImport } from './routes/over-ons.missie-visie'
import { Route as OverOnsMethodeRouteImport } from './routes/over-ons.methode'
import { Route as LovableOutreachScholenRouteImport } from './routes/lovable.outreach-scholen'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AanbodVerhuurRouteImport } from './routes/aanbod.verhuur'
import { Route as AanbodScholenRouteImport } from './routes/aanbod.scholen'
import { Route as AanbodEventsRouteImport } from './routes/aanbod.events'
import { Route as AanbodCommunityRouteImport } from './routes/aanbod.community'
import { Route as AanbodCommunityIndexRouteImport } from './routes/aanbod.community.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as AanbodCommunityKinderenRouteImport } from './routes/aanbod.community.kinderen'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const VoorwaardenRoute = VoorwaardenRouteImport.update({
  id: '/voorwaarden',
  path: '/voorwaarden',
  getParentRoute: () => rootRouteImport,
} as any)
const VisieRoute = VisieRouteImport.update({
  id: '/visie',
  path: '/visie',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ToegankelijkheidRoute = ToegankelijkheidRouteImport.update({
  id: '/toegankelijkheid',
  path: '/toegankelijkheid',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AanbodRoute = AanbodRouteImport.update({
  id: '/aanbod',
  path: '/aanbod',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsIndexRoute = OverOnsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OverOnsRoute,
} as any)
const AanbodIndexRoute = AanbodIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AanbodRoute,
} as any)
const OverOnsVerhaalRoute = OverOnsVerhaalRouteImport.update({
  id: '/verhaal',
  path: '/verhaal',
  getParentRoute: () => OverOnsRoute,
} as any)
const OverOnsMissieVisieRoute = OverOnsMissieVisieRouteImport.update({
  id: '/missie-visie',
  path: '/missie-visie',
  getParentRoute: () => OverOnsRoute,
} as any)
const OverOnsMethodeRoute = OverOnsMethodeRouteImport.update({
  id: '/methode',
  path: '/methode',
  getParentRoute: () => OverOnsRoute,
} as any)
const LovableOutreachScholenRoute = LovableOutreachScholenRouteImport.update({
  id: '/lovable/outreach-scholen',
  path: '/lovable/outreach-scholen',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AanbodVerhuurRoute = AanbodVerhuurRouteImport.update({
  id: '/verhuur',
  path: '/verhuur',
  getParentRoute: () => AanbodRoute,
} as any)
const AanbodScholenRoute = AanbodScholenRouteImport.update({
  id: '/scholen',
  path: '/scholen',
  getParentRoute: () => AanbodRoute,
} as any)
const AanbodEventsRoute = AanbodEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AanbodRoute,
} as any)
const AanbodCommunityRoute = AanbodCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AanbodRoute,
} as any)
const AanbodCommunityIndexRoute = AanbodCommunityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AanbodCommunityRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AanbodCommunityKinderenRoute = AanbodCommunityKinderenRouteImport.update({
  id: '/kinderen',
  path: '/kinderen',
  getParentRoute: () => AanbodCommunityRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aanbod': typeof AanbodRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/over-ons': typeof OverOnsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/toegankelijkheid': typeof ToegankelijkheidRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/visie': typeof VisieRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/aanbod/community': typeof AanbodCommunityRouteWithChildren
  '/aanbod/events': typeof AanbodEventsRoute
  '/aanbod/scholen': typeof AanbodScholenRoute
  '/aanbod/verhuur': typeof AanbodVerhuurRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lovable/outreach-scholen': typeof LovableOutreachScholenRoute
  '/over-ons/methode': typeof OverOnsMethodeRoute
  '/over-ons/missie-visie': typeof OverOnsMissieVisieRoute
  '/over-ons/verhaal': typeof OverOnsVerhaalRoute
  '/aanbod/': typeof AanbodIndexRoute
  '/over-ons/': typeof OverOnsIndexRoute
  '/aanbod/community/kinderen': typeof AanbodCommunityKinderenRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/aanbod/community/': typeof AanbodCommunityIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/toegankelijkheid': typeof ToegankelijkheidRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/visie': typeof VisieRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/aanbod/events': typeof AanbodEventsRoute
  '/aanbod/scholen': typeof AanbodScholenRoute
  '/aanbod/verhuur': typeof AanbodVerhuurRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lovable/outreach-scholen': typeof LovableOutreachScholenRoute
  '/over-ons/methode': typeof OverOnsMethodeRoute
  '/over-ons/missie-visie': typeof OverOnsMissieVisieRoute
  '/over-ons/verhaal': typeof OverOnsVerhaalRoute
  '/aanbod': typeof AanbodIndexRoute
  '/over-ons': typeof OverOnsIndexRoute
  '/aanbod/community/kinderen': typeof AanbodCommunityKinderenRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/aanbod/community': typeof AanbodCommunityIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aanbod': typeof AanbodRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/over-ons': typeof OverOnsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/toegankelijkheid': typeof ToegankelijkheidRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/visie': typeof VisieRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/aanbod/community': typeof AanbodCommunityRouteWithChildren
  '/aanbod/events': typeof AanbodEventsRoute
  '/aanbod/scholen': typeof AanbodScholenRoute
  '/aanbod/verhuur': typeof AanbodVerhuurRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lovable/outreach-scholen': typeof LovableOutreachScholenRoute
  '/over-ons/methode': typeof OverOnsMethodeRoute
  '/over-ons/missie-visie': typeof OverOnsMissieVisieRoute
  '/over-ons/verhaal': typeof OverOnsVerhaalRoute
  '/aanbod/': typeof AanbodIndexRoute
  '/over-ons/': typeof OverOnsIndexRoute
  '/aanbod/community/kinderen': typeof AanbodCommunityKinderenRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/aanbod/community/': typeof AanbodCommunityIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aanbod'
    | '/contact'
    | '/cookies'
    | '/disclaimer'
    | '/over-ons'
    | '/privacy'
    | '/sitemap.xml'
    | '/toegankelijkheid'
    | '/unsubscribe'
    | '/visie'
    | '/voorwaarden'
    | '/aanbod/community'
    | '/aanbod/events'
    | '/aanbod/scholen'
    | '/aanbod/verhuur'
    | '/email/unsubscribe'
    | '/lovable/outreach-scholen'
    | '/over-ons/methode'
    | '/over-ons/missie-visie'
    | '/over-ons/verhaal'
    | '/aanbod/'
    | '/over-ons/'
    | '/aanbod/community/kinderen'
    | '/api/public/contact'
    | '/lovable/email/suppression'
    | '/aanbod/community/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/cookies'
    | '/disclaimer'
    | '/privacy'
    | '/sitemap.xml'
    | '/toegankelijkheid'
    | '/unsubscribe'
    | '/visie'
    | '/voorwaarden'
    | '/aanbod/events'
    | '/aanbod/scholen'
    | '/aanbod/verhuur'
    | '/email/unsubscribe'
    | '/lovable/outreach-scholen'
    | '/over-ons/methode'
    | '/over-ons/missie-visie'
    | '/over-ons/verhaal'
    | '/aanbod'
    | '/over-ons'
    | '/aanbod/community/kinderen'
    | '/api/public/contact'
    | '/lovable/email/suppression'
    | '/aanbod/community'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/aanbod'
    | '/contact'
    | '/cookies'
    | '/disclaimer'
    | '/over-ons'
    | '/privacy'
    | '/sitemap.xml'
    | '/toegankelijkheid'
    | '/unsubscribe'
    | '/visie'
    | '/voorwaarden'
    | '/aanbod/community'
    | '/aanbod/events'
    | '/aanbod/scholen'
    | '/aanbod/verhuur'
    | '/email/unsubscribe'
    | '/lovable/outreach-scholen'
    | '/over-ons/methode'
    | '/over-ons/missie-visie'
    | '/over-ons/verhaal'
    | '/aanbod/'
    | '/over-ons/'
    | '/aanbod/community/kinderen'
    | '/api/public/contact'
    | '/lovable/email/suppression'
    | '/aanbod/community/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AanbodRoute: typeof AanbodRouteWithChildren
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DisclaimerRoute: typeof DisclaimerRoute
  OverOnsRoute: typeof OverOnsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ToegankelijkheidRoute: typeof ToegankelijkheidRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VisieRoute: typeof VisieRoute
  VoorwaardenRoute: typeof VoorwaardenRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableOutreachScholenRoute: typeof LovableOutreachScholenRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voorwaarden': {
      id: '/voorwaarden'
      path: '/voorwaarden'
      fullPath: '/voorwaarden'
      preLoaderRoute: typeof VoorwaardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visie': {
      id: '/visie'
      path: '/visie'
      fullPath: '/visie'
      preLoaderRoute: typeof VisieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toegankelijkheid': {
      id: '/toegankelijkheid'
      path: '/toegankelijkheid'
      fullPath: '/toegankelijkheid'
      preLoaderRoute: typeof ToegankelijkheidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aanbod': {
      id: '/aanbod'
      path: '/aanbod'
      fullPath: '/aanbod'
      preLoaderRoute: typeof AanbodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons/': {
      id: '/over-ons/'
      path: '/'
      fullPath: '/over-ons/'
      preLoaderRoute: typeof OverOnsIndexRouteImport
      parentRoute: typeof OverOnsRoute
    }
    '/aanbod/': {
      id: '/aanbod/'
      path: '/'
      fullPath: '/aanbod/'
      preLoaderRoute: typeof AanbodIndexRouteImport
      parentRoute: typeof AanbodRoute
    }
    '/over-ons/verhaal': {
      id: '/over-ons/verhaal'
      path: '/verhaal'
      fullPath: '/over-ons/verhaal'
      preLoaderRoute: typeof OverOnsVerhaalRouteImport
      parentRoute: typeof OverOnsRoute
    }
    '/over-ons/missie-visie': {
      id: '/over-ons/missie-visie'
      path: '/missie-visie'
      fullPath: '/over-ons/missie-visie'
      preLoaderRoute: typeof OverOnsMissieVisieRouteImport
      parentRoute: typeof OverOnsRoute
    }
    '/over-ons/methode': {
      id: '/over-ons/methode'
      path: '/methode'
      fullPath: '/over-ons/methode'
      preLoaderRoute: typeof OverOnsMethodeRouteImport
      parentRoute: typeof OverOnsRoute
    }
    '/lovable/outreach-scholen': {
      id: '/lovable/outreach-scholen'
      path: '/lovable/outreach-scholen'
      fullPath: '/lovable/outreach-scholen'
      preLoaderRoute: typeof LovableOutreachScholenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aanbod/verhuur': {
      id: '/aanbod/verhuur'
      path: '/verhuur'
      fullPath: '/aanbod/verhuur'
      preLoaderRoute: typeof AanbodVerhuurRouteImport
      parentRoute: typeof AanbodRoute
    }
    '/aanbod/scholen': {
      id: '/aanbod/scholen'
      path: '/scholen'
      fullPath: '/aanbod/scholen'
      preLoaderRoute: typeof AanbodScholenRouteImport
      parentRoute: typeof AanbodRoute
    }
    '/aanbod/events': {
      id: '/aanbod/events'
      path: '/events'
      fullPath: '/aanbod/events'
      preLoaderRoute: typeof AanbodEventsRouteImport
      parentRoute: typeof AanbodRoute
    }
    '/aanbod/community': {
      id: '/aanbod/community'
      path: '/community'
      fullPath: '/aanbod/community'
      preLoaderRoute: typeof AanbodCommunityRouteImport
      parentRoute: typeof AanbodRoute
    }
    '/aanbod/community/': {
      id: '/aanbod/community/'
      path: '/'
      fullPath: '/aanbod/community/'
      preLoaderRoute: typeof AanbodCommunityIndexRouteImport
      parentRoute: typeof AanbodCommunityRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aanbod/community/kinderen': {
      id: '/aanbod/community/kinderen'
      path: '/kinderen'
      fullPath: '/aanbod/community/kinderen'
      preLoaderRoute: typeof AanbodCommunityKinderenRouteImport
      parentRoute: typeof AanbodCommunityRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AanbodCommunityRouteChildren {
  AanbodCommunityKinderenRoute: typeof AanbodCommunityKinderenRoute
  AanbodCommunityIndexRoute: typeof AanbodCommunityIndexRoute
}

const AanbodCommunityRouteChildren: AanbodCommunityRouteChildren = {
  AanbodCommunityKinderenRoute: AanbodCommunityKinderenRoute,
  AanbodCommunityIndexRoute: AanbodCommunityIndexRoute,
}

const AanbodCommunityRouteWithChildren = AanbodCommunityRoute._addFileChildren(
  AanbodCommunityRouteChildren,
)

interface AanbodRouteChildren {
  AanbodCommunityRoute: typeof AanbodCommunityRouteWithChildren
  AanbodEventsRoute: typeof AanbodEventsRoute
  AanbodScholenRoute: typeof AanbodScholenRoute
  AanbodVerhuurRoute: typeof AanbodVerhuurRoute
  AanbodIndexRoute: typeof AanbodIndexRoute
}

const AanbodRouteChildren: AanbodRouteChildren = {
  AanbodCommunityRoute: AanbodCommunityRouteWithChildren,
  AanbodEventsRoute: AanbodEventsRoute,
  AanbodScholenRoute: AanbodScholenRoute,
  AanbodVerhuurRoute: AanbodVerhuurRoute,
  AanbodIndexRoute: AanbodIndexRoute,
}

const AanbodRouteWithChildren =
  AanbodRoute._addFileChildren(AanbodRouteChildren)

interface OverOnsRouteChildren {
  OverOnsMethodeRoute: typeof OverOnsMethodeRoute
  OverOnsMissieVisieRoute: typeof OverOnsMissieVisieRoute
  OverOnsVerhaalRoute: typeof OverOnsVerhaalRoute
  OverOnsIndexRoute: typeof OverOnsIndexRoute
}

const OverOnsRouteChildren: OverOnsRouteChildren = {
  OverOnsMethodeRoute: OverOnsMethodeRoute,
  OverOnsMissieVisieRoute: OverOnsMissieVisieRoute,
  OverOnsVerhaalRoute: OverOnsVerhaalRoute,
  OverOnsIndexRoute: OverOnsIndexRoute,
}

const OverOnsRouteWithChildren =
  OverOnsRoute._addFileChildren(OverOnsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AanbodRoute: AanbodRouteWithChildren,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DisclaimerRoute: DisclaimerRoute,
  OverOnsRoute: OverOnsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ToegankelijkheidRoute: ToegankelijkheidRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VisieRoute: VisieRoute,
  VoorwaardenRoute: VoorwaardenRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableOutreachScholenRoute: LovableOutreachScholenRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
