/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisieRouteImport } from './routes/visie'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AanbodRouteImport } from './routes/aanbod'
import { Route as IndexRouteImport } from './routes/index'

const VisieRoute = VisieRouteImport.update({
  id: '/visie',
  path: '/visie',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AanbodRoute = AanbodRouteImport.update({
  id: '/aanbod',
  path: '/aanbod',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aanbod': typeof AanbodRoute
  '/contact': typeof ContactRoute
  '/visie': typeof VisieRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aanbod': typeof AanbodRoute
  '/contact': typeof ContactRoute
  '/visie': typeof VisieRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aanbod': typeof AanbodRoute
  '/contact': typeof ContactRoute
  '/visie': typeof VisieRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aanbod' | '/contact' | '/visie'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aanbod' | '/contact' | '/visie'
  id: '__root__' | '/' | '/aanbod' | '/contact' | '/visie'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AanbodRoute: typeof AanbodRoute
  ContactRoute: typeof ContactRoute
  VisieRoute: typeof VisieRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visie': {
      id: '/visie'
      path: '/visie'
      fullPath: '/visie'
      preLoaderRoute: typeof VisieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aanbod': {
      id: '/aanbod'
      path: '/aanbod'
      fullPath: '/aanbod'
      preLoaderRoute: typeof AanbodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AanbodRoute: AanbodRoute,
  ContactRoute: ContactRoute,
  VisieRoute: VisieRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
